In [1]:
import numpy as np


In [7]:
alignment_mat = np.zeros((4,3))

print(alignment_mat)

alignment_mat[1,2] = 5

print('this is it', alignment_mat)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
this is it [[0. 0. 0.]
 [0. 0. 5.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
max_val = max(3,4,5)
print(max_val)

max_ind = np.argmax([3,4,5])
print(max_ind)

5
2


In [10]:
var = 'STRING'

print(var[2])

R
